### ISSUE TITLE
PR takes too long to process

### ISSUE THREAD

**Issue by PeterWinzell** [MEAE-GOT/W3C_VehicleSignalInterfaceImpl#15]
The PRs are not being processed fast enough. I suggest a timeout and then gatekeepers are permitted to push themselves. We will end up with merge hell and far too large commits otherwise.

**Comment by gunnarx** [comment]
At the moment there are no open PRs.  So I guess it got fixed :)

But reading this made me go to check the process (in the README).  It says that "gate keepers review and push to main branch", which seems to me to be more or less the same thing already?  Gatekeepers are the ones permitted to push (or merge).  If you're proposing to skip the PRs I'm not sure why, if gate keepers are still in control of the rate of merging?  The time that a PR stays open is already controlled by the same gate keepers?  There must be something that is not stated here under the surface... such as is the current expectation that _all_ gatekeepers approve each PR before _any_ gatekeeper merges it?

Overall, isn't the size of commits unrelated to the method discussed here?

**Comment by gunnarx** [comment]
Another detail that might help... I'm not sure where to find a definition of who are the "gate keepers" that the README refers to.

**Comment by PeterWinzell** [comment]
@gunnarx 
I agree, we need to discuss this through with the the other gatekeepers on the process.

**Comment by PeterWinzell** [comment]
Closing this issue. The current process "works" for now - as more people get involved we might have to adjust.
