### ISSUE TITLE
Duplicated HTML files

### ISSUE THREAD

**Issue by gunnarx** [MEAE-GOT/W3C_VehicleSignalInterfaceImpl#52]
There are duplicated HTML files.  Most of the time I just propose via PR but for some  it is easier to ask.

Do you prefer the html client example files to be in [client-1.0/Javascript](https://github.com/MEAE-GOT/W3C_VehicleSignalInterfaceImpl/tree/master/client/client-1.0/Javascript)

or in [client/webclients](https://github.com/MEAE-GOT/W3C_VehicleSignalInterfaceImpl/tree/master/client/webclients)?

(I will also remove the double versions that end in "2")

If webclients directory is preferred, is [this README]() useful?  It does not seem to be right anyway since it talks about the client, and not specifically the JavaScript directory.

(Actually now that I see it I assume the preferred directory is webclients, since JavaScript is now the only directory remaining under "client-1.0" and that directory has been removed for all other files. )

Just confirming...

**Comment by gunnarx** [comment]
On second look it seems the README is describing how to run the client, so that part should be included, I suppose, but moved up to the [client](https://github.com/MEAE-GOT/W3C_VehicleSignalInterfaceImpl/tree/master/client) directory.

**Comment by UlfBj** [comment]
Duplicate HTML files removed.
