### ISSUE TITLE
pre_dev ?

### ISSUE THREAD

**Issue by gunnarx** [MEAE-GOT/W3C_VehicleSignalInterfaceImpl#53]
Confirming once again, is it agreed that pre_dev directory should be deleted?

I also considered moving pre_dev and any similar files underneath a top-level directory named "extra/" as a temporary.  Which do you prefer?

**Comment by gunnarx** [comment]
For example, w3cDemo directory could also be kept in extra.
(or removed).  Which do you prefer?

**Comment by MagnusGun** [comment]
pre_dev is removed
