### ISSUE TITLE
GOPATH clarity

### ISSUE THREAD

**Issue by basanjeev** [MEAE-GOT/W3C_VehicleSignalInterfaceImpl#66]
The README.md does not clearly define how to set GOPATH.
Maybe this is trivial, but it would be helpful for beginners.
I found the following issue after trying to start the servers.
```
vssparserutilities.c:208:17: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  208 |                 fread(node2->function, sizeof(char)*node2->functionLen, 1, treeFp);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/MEAE-GOT/W3C_VehicleSignalInterfaceImpl/server/server-core
./servercore.go:830:18: undefined: utils.GetModelIP
./servercore.go:830:35: undefined: utils.IpModel

```

**Comment by UlfBj** [comment]
If you use GO modules, setting GOPATH should not be necessary. 
Try use the command below to download all dependencies. (util modules should be included in that)
go get -u ./...

**Comment by MagnusGun** [comment]
I'm closing this issue since no update from Sanjeev for long time!
