### ISSUE TITLE
Client API usage

### ISSUE THREAD

**Issue by basanjeev** [MEAE-GOT/W3C_VehicleSignalInterfaceImpl#75]
Please provide a full list of "signal paths" that are supported (based on the currently supported data models).
More details on
1. URI for agt-server (http://localhost:8500/agtserver)
`curl -i -d "{\"userid\": \"ABCD\", \"vin\":\"HYUNDAI\"}\" -X POST http://localhost:8500/agtserver

**Response**
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Date: Tue, 11 Feb 2020 15:13:21 GMT
Content-Length: 329
Content-Type: text/plain; charset=utf-8

{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImlzcyI6Im9lbS5jb20vZ2VuMi9iYWNrZW5kIiwic2lndXJsIjoib2VtLmNvbS9nZW4yL2JhY2tlbmQvcHViIiwiaWF0IjoxNTc3ODQ3NjAwLCJleHAiOjE1OTM1NjE1OTksImp0aSI6IjQ2NjdlOTNmLTQwZjktNWYzOS04OTNlLWNjMGRhODkwZGIzZiJ9.eyJ1aWQiOiJzYW5qZWV2IiwiYXVkIjoiSFlVTkRBSSJ9.csoBK10HTMoArWKdO_EU_I9AH-JGbAvcOKyZXoIkOrU"}
`

2. URI for at-server(http://localhost:8600/atserver)
`curl -i -d "{\"scope\":\"VehicleControl\",\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImlzcyI6Im9lbS5jb20vZ2VuMi9iYWNrZW5kIiwic2lndXJsIjoib2VtLmNvbS9nZW4yL2JhY2tlbmQvcHViIiwiaWF0IjoxNTc3ODQ3NjAwLCJleHAiOjE1OTM1NjE1OTksImp0aSI6IjQ2NjdlOTNmLTQwZjktNWYzOS04OTNlLWNjMGRhODkwZGIzZiJ9.eyJ1aWQiOiJzYW5qZWV2IiwiYXVkIjoiSFlVTkRBSSJ9.csoBK10HTMoArWKdO_EU_I9AH-JGbAvcOKyZXoIkOrU\"}" -X POST http://localhost:8600/atserver
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Date: Tue, 11 Feb 2020 15:44:44 GMT
Content-Length: 321
Content-Type: text/plain; charset=utf-8

{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk0NTkxOTksImF1ZCI6IkdlbjIiLCJzY3AiOiJWZWhpY2xlQ29udHJvbCIsImp0aSI6IjU5NjdlOTNmLTQwZjktNWYzOS04OTNlLWNjMGRhODkwZGIyZSIsInVpZCI6InNhbmplZXYiLCJpc3MiOiJIWVVOREFJIiwic2lndXJsIjoidzMub3JnL2dlbjIvdXNlci9wdWIvc2FuamVldiJ9.3oDAeSXaD_iDMuNP4aDXuNmZTDCTX3PcUDfXYs133H8"}
`
3. 8081 - transport registration
4. 8082 - service registration

How to use the above two ports?

**Comment by UlfBj** [comment]
>> Please provide a full list of "signal paths" that are supported (based on the currently supported data models).

The server supports the VSS tree available in the file server/server-core/vss_rel_2.0.0-alpha+006.cnative. This file has been generated from the latest VSS vspec data for not so long time ago. It can be generated again on any VSS repo by generating the command "make cnative", after building the cnative tools as described in the README on vehicle_signal_specification/tools/c_native/. 
The list of signal path can be found in vehicle_signal_specification/blob/master/spec/VehicleSignalSpecification.id. 

>> 8081 - transport registration
8082 - service registration
How to use the above two ports?

These are server internal ports, not to be used explicitly by a client. The http manager and Websocket manager register themselves with the core server using 8081. The service manager registers using 8082. 

>> localhost:8600/agtserver

The URI for the at-server shall be localhost:8600/atserver
