### ISSUE TITLE
Hyphen in payload

### ISSUE THREAD

**Issue by UlfBj** [MEAE-GOT/W3C_VehicleSignalInterfaceImpl#77]
The request
{'action':'subscribe', 'path':'Vehicle.Cabin.Door.Row1.Right.IsOpen', 'filter':'$intervalEQ2', 'requestId':'239'}
If replacing the ' characters with " characters:
{"action":"subscribe", "path":"Vehicle.Cabin.Door.Row1.Right.IsOpen", "filter":"$intervalEQ2", "requestId":"239"}
 then it works as expected. 
It should work with both.

**Comment by MagnusGun** [comment]
Using single quotes breaks JSON syntax that require double quotes for JSON names
https://www.w3schools.com/js/js_json_syntax.asp

**Comment by UlfBj** [comment]
Thanks for pointing it out. I guess we can close the issue then.

**Comment by MagnusGun** [comment]
ok closing issue
